##https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multi-binder-samples/multi-binder-dynamic-destinations/src/main/resources/application.yml
#spring.cloud.stream:
#  function.definition: supplier;receive1;receive2;
#  bindings:
#    receive1-in-0.destination: customerId-1
#    receive2-in-0.destination: customerId-2